baseURL = ""
languageCode = "ja-ja"
title = "じんせいをかくかくかく"
canonifyURLs = false
relativeURLs = true
disableHugoGeneratorInject = true
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/:section/:year/:month/:title"

[build]
  command = "yarn build"
  publish = "dist"
