baseURL = ""
languageCode = "ja-ja"
title = "lightly"
canonifyURLs=false
relativeURLs=true
disableHugoGeneratorInject = true

[permalinks]
  blog = "/:section/:title"

[build]
  command = "yarn build"
  publish = "dist"
