baseURL = "https://www.t4traw.net"
languageCode = "ja-ja"
title = "すきせか"
canonifyURLs = false
relativeURLs = true
disableHugoGeneratorInject = true
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true
rssLimit = 15
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
  name = "t4traw"
  email = "t4traw@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  blog = "/:section/:year/:month/:title"

[build]
  command = "yarn build"
  publish = "dist"

[related]
  threshold = 80
  includeNewer = true
  toLower = true
[[related.indices]]
  name = "categories"
  weight = 150
[[related.indices]]
  name  = "tags"
  weight = 100
[[related.indices]]
  name  = "date"
  pattern = "2006"
  weight = 100