baseURL = "https://t4traw.net"
languageCode = "ja-ja"
title = "t4traw.net"
canonifyURLs = false
relativeURLs = true
disableHugoGeneratorInject = true
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true
rssLimit = 15

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[author]
  name = "t4traw"
  email = "t4traw@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  archive = "archives"

[permalinks]
  blog = "/:year/:month/:filename"

[build]
  command = "npm run now-build"
  publish = "dist"

[related]
  threshold = 80
  includeNewer = true
  toLower = true
[[related.indices]]
  name = "categories"
  weight = 150
[[related.indices]]
  name  = "tags"
  weight = 100
[[related.indices]]
  name  = "date"
  pattern = "2006"
  weight = 100